# Linux driver folder
#EXTRA_CFLAGS +=-Wno-error=date-time
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/gt9xx_android/
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

#obj-y	+=  gt9xx.o
#obj-y	+=  gt9xx_update.o
#obj-y	+=  goodix_tool.o


obj-$(CONFIG_GT9XX_V2_4)        += gt9xx.o goodix_tool.o gt9xx_update.o 
