name: Build Kernel

on:
  push:
    paths:
      - '.github/workflows/build-uboot.yml'
      - 'u-boot/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: /usr/local/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu
          key: gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu

      - name: Install toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: u-boot
        run: |
          wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
          sudo tar xvf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz  -C /usr/local/

      - name: Build kernel
        working-directory: u-boot
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=/usr/local/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
          make  evb-rk3399_defconfig
          ./make.sh rk3399
          

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: JJ31-uboot
          path: |
            u-boot/**.bin
            u-boot/**.img


          if-no-files-found: ignore
